package app.dal.entities;

// Generated Oct 31, 2012 1:45:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersRolesId generated by hbm2java
 */
@Embeddable
public class UsersRolesId implements java.io.Serializable {

	private int userId;
	private int roleId;

	public UsersRolesId() {
	}

	public UsersRolesId(int userId, int roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersRolesId))
			return false;
		UsersRolesId castOther = (UsersRolesId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
